import Head from "next/head";

import { Chat } from "@/components/room/chat";
import { RoomList } from "@/components/room/list";
import { UserList } from "@/components/user/list";
import { api } from "@/utils/api";

export default function Home() {
  const user = api.user.getAll.useQuery();

  if (!user) {
    return <div>Loading...</div>;
  }

  return (
    <>
      <Head>
        <title>Trpc Chat</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen">
        <aside className="flex min-h-screen max-w-[150px] flex-col border-r">
          <RoomList />
          <UserList />
        </aside>
        <main className="just flex w-full items-center justify-center">
          <Chat />
        </main>
      </div>
    </>
  );
}

// function Header() {
//   const { data: sessionData } = useSession();

//   return (
//     <div className="flex items-center justify-center gap-4 p-8">
//       <p className="text-2x text-center">
//         {sessionData && <span>{sessionData.user?.name}</span>}
//       </p>
//       <Button
//         variant={"outline"}
//         onClick={sessionData ? () => void signOut() : () => void signIn()}
//       >
//         {sessionData ? "Sign out" : "Sign in"}
//       </Button>
//     </div>
//   );
// }
